// Werewolf Game - Translations (English)
const LANG = {
  en: {
    'join-title': 'Join Werewolf',
    'join-subtitle': 'Enter your username to join the game.',
    'username-placeholder': 'Enter your username',
    'join-btn': 'Join Game',
    'join-error': 'Failed to join. Check the room code.',
    'enter-code-label': 'Room Code',
    'enter-code-placeholder': 'Enter room code',
    'scan-to-join': 'or scan the QR code',
    'waiting-title': 'Waiting for host...',
    'waiting-subtitle': 'The game will start when the host begins.',
    'players-joined': 'players joined',
    'connected': 'Connected',
    'disconnected': 'Disconnected',
    'lobby-title': 'Room Code',
    'copy-code': '📋 Copy Code',
    'scan-qr': 'Scan to join',
    'total': 'Total',
    'online': 'Online',
    'offline': 'Offline',
    'alive': 'Alive',
    'dead': 'Dead',
    'round': 'Round',
    'start-game': '▶ Start Game',
    'end-game': '✕ End Game',
    'new-game': '🔄 New Game',
    'wolf-count': 'Werewolves:',
    'role-dist': 'Role Distribution',
    'waiting-players': 'Waiting for players...',
    'create-game': '🎮 Create Game',
    'landing-title': 'Werewolf',
    'landing-subtitle': 'A game of deception and deduction',
    'players': 'Players',
    'kick': 'Kick',
    'night': 'Night',
    'night-falls': 'Night falls...',
    'day': 'Day',
    'discussion': 'Discussion',
    'voting': 'Voting',
    'results': 'Results',
    'victory': 'Victory',
    'process-night': '🌙 Process Night',
    'process-day': '☠️ Eliminate',
    'continue': '▶ Continue',
    'start-voting': '🗳️ Start Voting',
    'doctor-saved': '💉 No one died — the Doctor saved them!',
    'no-one-died': '🌅 No one died',
    'was-killed': 'was killed',
    'was-eliminated': 'was eliminated!',
    'killed-by-mark': 'killed by the Wolf King\'s mark!',
    'vote-tally': 'Vote Tally',
    'no-votes': 'No votes cast',
    'votes': 'votes',
    'village-wins': '🏆 Village Wins!',
    'werewolf-wins': '🐺 Werewolves Win!',
    'final-words': 'Final Words',
    'player-list': 'Players',
    'villager': 'Villager',
    'werewolf': 'Werewolf',
    'wolf_king': 'Wolf King',
    'seer': 'Seer',
    'doctor': 'Doctor',
    'shooter': 'Shooter',
    'villager-desc': 'Use your intuition to find the werewolves during the day.',
    'werewolf-desc': 'Each night, choose a victim with your pack.',
    'wolf_king-desc': 'Each night, kill with your pack and secretly mark one target. If you die, your marked target dies too.',
    'seer-desc': 'Each night, investigate one player to learn if they are Good or Bad.',
    'doctor-desc': 'Each night, protect one player from the werewolves. Cannot protect yourself or the same player twice in a row.',
    'shooter-desc': 'You have no night action, but if eliminated, you may take one revenge shot.',
    'team-village': 'Village Team',
    'team-werewolf': 'Werewolf Team',
    'choose-target': 'Choose your target',
    'choose-kill': 'Choose a victim to kill',
    'choose-mark': 'Choose a player to mark',
    'choose-protect': 'Choose a player to protect',
    'choose-investigate': 'Choose a player to investigate',
    'choose-revenge': 'Choose your revenge target',
    'confirm-action': 'Confirm',
    'action-submitted': '✅ Action submitted',
    'targeting': 'targeting',
    'waiting-others': 'Waiting for other players...',
    'close-eyes': 'Close your eyes and wait...',
    'got-it': 'Got it!',
    'investigation-result': 'Investigation Result',
    'good': '🤝 Good',
    'bad': '☠️ Bad',
    'mark-placed': '🎯 Mark placed',
    'villager-waiting': 'As a Villager, you have no night action. Wait for the night to end.',
    'revenge-title': '💀 Revenge Shot',
    'revenge-desc': 'You have one revenge shot! Choose who to take down with you.',
    'shoot': '🔫 Shoot',
    'you-died': '💀 You are dead',
    'your-role-was': 'Your role was:',
    'final-words-label': 'Your final words:',
    'final-words-placeholder': 'Write your final words...',
    'submit': 'Submit',
    'spectating': '👁️ Spectating',
    'wolf-chat': '🐺 Wolf Chat',
    'wolf-chat-placeholder': 'Message the pack...',
    'send': 'Send',
    'advertisement': 'Advertisement — Support Werewolf',
    'play-again': '🔄 Play Again',
    'leave': 'Leave Game',
    'you': '(You)',
    'unknown': 'Unknown',
  }
};

let lang = 'en';

function t(key) {
  return (LANG[lang] && LANG[lang][key]) || key;
}

function setLang(l) {
  lang = l;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    el.textContent = t(el.dataset.i18n);
  });
}
